name    'debmirror'
version '0.0.1'
source  'UNKNOWN'
author  'Xavier Logerais'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'Puppet module to manage debmirror'
project_page 'https://github.com/xlogerais/puppet-module-debmirror'
